### ISSUE TITLE
use regex to make a pattern for LOGICAL OR operator

### ISSUE THREAD

**Issue by fatems** [mehrbanian/sutech-compiler-1400#3]
i have issues using regex to write a pattern to take out || (logical or) from our input file, 
i've used this regex pattern to match "or operator" from input but the issue is that it takes every '|' character out of the input and turns it back as the OR operator token, but what i want is to return '||' as the "logical OR operator token" .

from what i've searched i know that we have to use the escape character to get it working for example by writing:
("\\|\\|") or ("\\||") we'd have it working but as i said its not working for me 

i've even tried ("\\|{2}") to emphasize  the character have to repeat exactly 2 times, if we consinde "          ||       " our input, the output will be two "or operator" and the lexeme for each of them will be "|".

any ideas?

any help would be appreciated.

**Comment by soroushahrari** [comment]
As you said these two patterns (\|\| and \|{2}) should work. There may be a problem in your code.

**Comment by fatems** [comment]
> 
> 
> As you said these two patterns (|| and |{2}) should work. There may be a problem in your code.

i dunno i dont think so.

**Comment by fatems** [comment]
actually the one "||" will cause to a big bug and returns everything as or operator because | is used in regex to seperate different patterns and point it out to just one token , its working for everything but the ones with two characters such as || and ++ , -- , ==

**Comment by fatems** [comment]
actually the one "||" will cause to a big bug and returns everything as or operator because | is used in regex to seperate different patterns and points them out to just one token , its working for everything but the ones with two characters such as || and ++ , -- , ==, <+ and so on

**Comment by soroushahrari** [comment]
I meant `\|\|`, Github removed `\` character. The same approach should work for all two-character tokens. you can test and validate your regex [here](( https://regex101.com)). I don't have any clue. Maybe there is a problem with the library/tool that you are using.

**Comment by mehrbaniyan** [comment]
Hi @fatems,
If `\|\|` didn't work, try using `\\|\\|`
As @soroushahrari suggested, this issue might be related to your code.
Please let me know if this solved your problem.

**Comment by fatems** [comment]
@soroushahrari @mehrbanian i had problems defining other tokens and their order. this solved my issue, thank you.

**Comment by mehrbaniyan** [comment]
Good luck.
